### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by jjennings955** [HyperGAN/HyperGAN#79]
I know Windows support probably isn't much of a priority, but it seems like there are a very small number of barriers to Windows compatibility (out of the box) for HyperGAN.

1. tf.contrib.ffmpeg - Not supported, but only necessary for audio tasks. I propose something like the following in hypergan/loaders/audio_loaders.py:
```python
try:
    from tensorflow.contrib import ffmpeg
except ImportError:
    import warnings
    warnings.warn("ffmpeg support not found, audio loaders will not work!")```
```
2. fcntl - I'll be honest I have no idea what this does, but it seems to only be used once in cli.py for ipython support.

I propose something like:
```python
        if(self.args.ipython):
            import fcntl # Move the import into the if statement (remove from top)
            fd = sys.stdin.fileno()
            fl = fcntl.fcntl(fd, fcntl.F_GETFL)
            fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)
```

This way there would only be an error thrown if someone is trying to use a feature their OS doesn't support, rather than "import hypergan" failing.

Thanks.

**Comment by DippedPretzels** [comment]
I agree - there were only a few tweaks I needed to get it running (I haven't tested all the functions however) in win10, and adding Windows support would likely bring more users. 

1. This is a good idea.

2. I followed this comment: [](http://stackoverflow.com/a/25471508) to solve this issue, but your solution is better.

I also ran into the issue that tf.one_hot was trying to use GPU instead of CPU, and failing (it seems other people have issues with tf.one_hot and GPUs in Windows.  This was solved in gan.py, by adding a line "with tf.device('/cpu:0'):"

```
	# convert to one-hot
        with tf.device('/cpu:0'):
        	graph.y=tf.cast(graph.y,tf.int64)
                graph.y=tf.one_hot(graph.y, self.config['y_dims'], 1.0, 0.0) 

```

I've only tested the master branch in Windows, but I can train WGAN and LSGAN just fine.

**Comment by martyn** [comment]
I don't have a windows machine to test with, but I'm happy to merge a windows PR.

**Comment by europax** [comment]
I wrote a tutorial on how to run it on Windows in #72.

**Comment by martyn** [comment]
Windows installation will be simplified in 1.0 now that it uses pytorch. Also we're planning a windows installer.
